### ISSUE TITLE
UnicodePwd vs userPassword

### ISSUE THREAD

**Issue by nathanr801** [Zimbra-Community/ADPassword#12]
ADPassword appears to be working how it's supposed to except that my organization uses userPassword instead of UnicodePwd. So when the password is changed in Zimbra, it sets the UnicodePwd instead of the userPassword. Any suggestions are appreciated.

**Comment by ghost** [comment]
is this on a sun ldap?

**Comment by nathanr801** [comment]
OpenLDAP

**Comment by ghost** [comment]
I can provide a separate version for EUR 50.

**Comment by nathanr801** [comment]
I considered it but will say no. A sincere "Thank You!" for your excellent work on this so far!
