### ISSUE TITLE
Cant Bind

### ISSUE THREAD

**Issue by javito1081** [Zimbra-Community/ADPassword#13]
I havent been able to figure it out yet and i didnt find an email or something to contact u barry, i hope this gets to u so if u have time u can help me figure it out cause i dont know what else to do, i setup everything exactly as in your guide, i can authenticate all my domain users using ldaps no problem, but when they try to change their password they get permission denied error, heres the log on CLI

```
2019-09-29 21:20:27,584 INFO  [qtp1911152052-140://localhost:8080/service/soap/ChangePasswordRequest] [ua=zclient/8.8.15_GA_3869;soapId=1b38e5bb;] soap - ChangePasswordRequest elapsed=99
2019-09-29 21:20:27,588 WARN  [qtp1911152052-20:https://mailer.testing.com/h/changepass?skin=harmony] [] webclient - permission denied: javax.naming.CommunicationException: simple bind failed: server-ad:636 [Root exception is java.net.SocketException: Connection or outbound has closed]
com.zimbra.common.soap.SoapFaultException: permission denied: javax.naming.CommunicationException: simple bind failed: server-ad:636 [Root exception is java.net.SocketException: Connection or outbound has closed]
ExceptionId:qtp1911152052-140:1569810027580:fd49cf62b9d1eb5c
Code:service.PERM_DENIED
```

**Comment by ghost** [comment]
If this is Windows 2008 or higher, you may not have it enabled with SSL: 
[ https://github.com/Zimbra-Community/ADPassword/wiki/Enable-LDAPS-on-Windows-2008-Active-Directory-Domain | https://github.com/Zimbra-Community/ADPassword/wiki/Enable-LDAPS-on-Windows-2008-Active-Directory-Domain ] 

Double check your if you entered the correct host `server-ad:636` and you may need to set a firewall rule. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by javito1081** [comment]
i forgot to add that i believe its a certificate issue, cause if i issue the following command:

`ldapsearch -x -H ldaps://10.0.1.6:636 -D 'CN=Administrator,CN=Users,DC=vpn,DC=com' -w 'my pass' -s sub -b "CN=Users,DC=vpn,DC=com"`

i get a full response with all my ldap info, BUT only if i add TLS_REQCERT NEVER to the /etc/ldap/ldap.conf

Im using server 2019 with a 2012 domain/forrest, ill upgrade it 2016 withing the next few weeks but for now thats what im using

Also, i followed this procedure to create and import the cert https://wiki.zimbra.com/wiki/Secure_Authentication_between_Zimbra_and_AD

and this is how my inf look like

`;----------------- csr.inf ----------------- 
  
[Version] 

Signature="$Windows NT$" 

[NewRequest]

Subject = "CN=server-ad.vpn.com" 
; Replace <DC fqdn> with the FQDN of your DC.
; Replace the remaining Subject attributes.
KeySpec = 1 
KeyLength = 2048 
HashAlgorithm = SHA256
Exportable = TRUE 
MachineKeySet = TRUE 
SMIME = False 
PrivateKeyArchive = FALSE 
UserProtected = FALSE 
UseExistingKeySet = FALSE 
ProviderName = "Microsoft RSA SChannel Cryptographic Provider" 
ProviderType = 12
RequestType = PKCS10 
KeyUsage = 0xa0 

[EnhancedKeyUsageExtension] 

OID=1.3.6.1.5.5.7.3.1 ; this is for Server Authentication

;-----------------------------------------------`
 
ill read the links u gave me and see if im missing something, casue i definetly can connect to my ldap on port 636, but aparently the problem ether lies on the cert or something else :(

**Comment by ghost** [comment]
you must add the cert to the zimbra keystore as well and restart mailbox for it to work.

But I would expect to see a different error in the log

**Comment by javito1081** [comment]
> you must add the cert to the zimbra keystore as well and restart mailbox for it to work. But I would expect to see a different error in the log
> […](#)
> On 30 Sep 2019, at 09:28, Javier Duran ***@***.***> wrote: i forgot to add that i believe its a certificate issue, cause if i issue the following command: ldapsearch -x -H ldaps://10.0.1.6:636 -D 'CN=Administrator,CN=Users,DC=vpn,DC=com' -w 'my pass' -s sub -b "CN=Users,DC=vpn,DC=com" i get a full response with all my ldap info, BUT only if i add TLS_REQCERT NEVER to the /etc/ldap/ldap.conf Im using server 2019 with a 2012 domain/forrest, ill upgrade it 2016 withing the next few weeks but for now thats what im using Also, i followed this procedure to create and import the cert https://wiki.zimbra.com/wiki/Secure_Authentication_between_Zimbra_and_AD and this is how my inf look like `;----------------- csr.inf ----------------- [Version] Signature="$Windows NT$" [NewRequest] Subject = "CN=server-ad.vpn.com" ; Replace with the FQDN of your DC. ; Replace the remaining Subject attributes. KeySpec = 1 KeyLength = 2048 HashAlgorithm = SHA256 Exportable = TRUE MachineKeySet = TRUE SMIME = False PrivateKeyArchive = FALSE UserProtected = FALSE UseExistingKeySet = FALSE ProviderName = "Microsoft RSA SChannel Cryptographic Provider" ProviderType = 12 RequestType = PKCS10 KeyUsage = 0xa0 [EnhancedKeyUsageExtension] OID=1.3.6.1.5.5.7.3.1 ; this is for Server Authentication ;-----------------------------------------------` ill read the links u gave me and see if im missing something, casue i definetly can connect to my ldap on port 636, but aparently the problem ether lies on the cert or something else :( — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

i did, with the following command:

`sudo /opt/zimbra/common/bin/keytool -import -alias win2012 -keystore /opt/zimbra/common/etc/java/cacerts -trustcacerts -file ad.cer
`

and then restarted with `zmcontrol restart` but still the same :-(

i read the link u gave me but the **Domain Controller** and **Domain Controller Authentication** policy's are unavailable since i dont have ADCS installed, i uninstalled it before creating my own with the zimbra wiki procedure, do u think i should remove that and try the method on the website u gave me?

**Comment by javito1081** [comment]
oh and if i modify the ldap database on /etc/ldap/ldap.conf to

`TLS_CACERT    /opt/zimbra/common/etc/java/cacerts                         (Same zimbra is using)`
 and comment `# TLS_REQCERT never` and try to run the ldapsearch command again, i get `ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)`

if i add -d1 i get

```
ldap_url_parse_ext(ldaps://10.0.1.6:636)
ldap_create
ldap_url_parse_ext(ldaps://10.0.1.6:636/??base)
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 10.0.1.6:636
ldap_new_socket: 3
ldap_prepare_socket: 3
ldap_connect_to_host: Trying 10.0.1.6:636
ldap_pvt_connect: fd: 3 tm: -1 async: 0
attempting to connect: 
connect success
TLS: peer cert untrusted or revoked (0x42)
TLS: can't connect: (unknown error code).
ldap_err2string
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

```

**Comment by javito1081** [comment]
Well i finally fixed my issue, followed the procedures on https://github.com/Zimbra-Community/ADPassword/wiki/Enable-LDAPS-on-Windows-2008-Active-Directory-Domain and imported both certificates generated by **Domain Controller** and **Domain Controller Authentication**, also i had to use the fqdn instead of the ip in the ldaps server field, if i use the ip i get an error, idk how u issue the certificate on ur youtube video but aparently that doesnt work anymore if u use the ip.

Theres a new issue now with users in OU's instead of CN's but i guess ill open a new issue for that since the problem is now resolved.

**Comment by ghost** [comment]
tls can only work with domain names indeed, perhaps, in some older version of Zimbra 
cert validation was turned off by default. 

I will make a not of this in the readme. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
