### ISSUE TITLE
zimbra 8.8.15 5p  ( java 13)

### ISSUE THREAD

**Issue by eq-pepe** [Zimbra-Community/ADPassword#15]
ADpassword work perfect up to zimbra 8.8.15 4p , in last patch 5p they change java form 11 (11.0.2-1zimbra8.8b1.16.04) to 13. (13.0.1-1zimbra8.8b1.16.04) and all auth will cause to unable to login in admin :7071 and user unable to login too. 

The following packages have been updated by 8.8.15_Patch5 (on an Ubuntu 16.04): 
zimbra-common-core-jar zimbra-common-core-libs zimbra-core-components zimbra-drive zimbra-mbox-store-libs zimbra-mbox-war zimbra-openjdk zimbra-patch

Actual work arroud is only downgrade to p4 
apt install -f zimbra-common-core-jar=8.8.15.1569887376-1.u16
apt install -f zimbra-common-core-libs=8.8.15.1569886566-1.u16
apt install -f zimbra-core-components=2.0.0-1zimbra8.8b1.16.04
apt install -f zimbra-drive=1.0.13.1574269069-1.u16
apt install -f zimbra-mbox-store-libs=8.8.15.1569886566-1.u16
apt install -f zimbra-openjdk=11.0.2-1zimbra8.8b1.16.04

errors from zmmailboxd.out
oejs.HttpChannel:qtp366590980-453: /service/admin/soap/GetDomainInfoRequest
javax.servlet.ServletException: javax.servlet.UnavailableException: com/sun/net/ssl/internal/ssl/Provider at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:168)

javax.servlet.UnavailableException: com/sun/net/ssl/internal/ssl/Provider
        at com.zimbra.soap.SoapServlet.init(SoapServlet.java:135)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
... 

in new java 13 oracle remove off the Internal com.sun.net.ssl Package and is no longer supported.
Standard replacement APIs such as HostNameVerifier, KeyManager, and TrustManager have been available in the javax.net.ssl package. i hope this help fix this Issue

**Comment by ghost** [comment]
Thanks for reporting, I probably need to port some Java code to the latest 
version of Java, 

It may take me a while to get around to this, in the meantime please use the older 
version of Java or uninstall adpassword. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by ghost** [comment]
Hello, can you please check f it works with the new version. 

     wget https://github.com/Zimbra-Community/ADPassword/raw/master/out/artifacts/ADPassword_jar/ADPassword.jar -O /opt/zimbra/lib/ext/adpassword/adPassword.jar 
     su zimbra
     zmcontrol restart

**Comment by ghost** [comment]
Please report back, so I can close this ticket, thanks!

**Comment by eq-pepe** [comment]
Hi Barry
Thanx for feedback. For me it is actual no problem i perform downgrade back to 4patch with Java 11 but for others can by problem in production because this change for Java 13 affect also other zimlets

Peter

**Comment by eq-pepe** [comment]
I can try it tommorow 
Thanx

Peter

**Comment by eq-pepe** [comment]
Hi Barry

This patch support both version of Java or just 13? If both i can test it on actual 11 and then on 13. 

Peter

**Comment by ghost** [comment]
I compiled it for 13.

But it would be nice to know if it works on 11.

**Comment by eq-pepe** [comment]
Hi Barry

Sorry for delay. 
Result from testing :

With patch4 (Java 11) new adpassword works as before with no probs. 
With patch5 (Java 13) new adpassword didnt work same errors as with actual ver. 

I thing there is problem with SSL method you must use new see change log for Java 13

Peter

> Dňa 28. 12. 2019 o 11:28 užívateľ Barry de Graaff <notifications@github.com> napísal:
> 
> ﻿I compiled it for 13. 
> 
> But it would be nice to know if it works on 11. 
>

**Comment by ghost** [comment]
Hello,

I have just tested it on an 8.8.15 patch 5 FOSS server, and it works fine. Perhaps you have an old copy of the ADPassword jar in your /opt/zimbra somewhere, it may even be loaded if it is renamed, so make sure to REMOVE any old adpassword.jar completely.

As of Zimbra 8.8.15 you MUST configure your AD server by it's DNS FQDN, you cannot use the change password extension by using the IP of your AD. This is because Java only proceeds if the SSL certificate matches the domain name in the configuration. (zimbraAuthLdapURL must be a domain, example of self signed windows cert: zmprov md barrydegraaff.tk zimbraAuthLdapURL "ldaps://WIN-M7ME1BSBTRY.barrydegraaff.tk:636")

Here is my test env:

         [zimbra@zimbra8x root]$ zmcontrol -v
         Release 8.8.15_GA_3869.RHEL7_64_20190917004220 RHEL7_64 FOSS edition, Patch 8.8.15_P5.
         [zimbra@zimbra8x root]$ exit
         exit
         [root@zimbra8x ~]# ls -hal  /opt/zimbra/common/lib/jvm/java
         lrwxrwxrwx. 1 root root 21 Jan  5 10:07 /opt/zimbra/common/lib/jvm/java -> openjdk-13.0.1-zimbra

Do a `tail -f /opt/zimbra/log/*`  and then try and change a password, hit CTRL+C in the terminal and see what Java exception is logged.
