### ISSUE TITLE
How to compile the latest version of ADPassword

### ISSUE THREAD

**Issue by Wodel** [Zimbra-Community/ADPassword#17]
Hi,

I am a sysadmin, I don't know much about java.
With previous versions of ADPassword, I made some changes to the source to be able to change password on Fedora's 389 Directory Server.
And I was able to compile the source code using just ANT.
This last version doesn't contain the nbproject directory and I found the ADPassword.iml
If I understand correctly intellij is used instead of netbeans.
I am searching for the simplest way to compile this code to be able to use the connector with 389 DS.
And as I said, I really don't know much about java.

Regards.

**Comment by barrydegraaff** [comment]
You can go here: 
[ https://www.jetbrains.com/idea/download/#section=linux | https://www.jetbrains.com/idea/download/#section=linux ] 

Download the latest community edition, make changes and rebuild the project from the UI. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by ghost** [comment]
Added build.xml for compilation using ant. There is also a wrapper for gnu make. So you can run `make` to compile.
