### ISSUE TITLE
Problem with AD 2003

### ISSUE THREAD

**Issue by eduardpalomo** [Zimbra-Community/ADPassword#19]
Hi, I am implementing a zimbra 8.8.15 against an AD level of functionality 2003 with Windows 2008R2 servers, the authentication part works fine but the password change always denied, under the losg copy, I would be very grateful for your help.
PD: the password is already validated and that is not the problem.

2020-03-03 12: 25: 47,312 WARN [qtp1225197672-122: https: //zimbra.aviacioncivil.gob.ec/h/changepass] [] webclient - permission denied: javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1?]
com.zimbra.common.soap.SoapFaultException: permission denied: javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1?]
ExceptionId: qtp1225197672-114: 1583256347308: e97542d44c28f0a0
Code: service.PERM_DENIED

**Comment by ghost** [comment]
This extension was not tested on Windows 2008 for 4 years or so. That said it probably still works.

The error above indicates a wrong password, of you are using a bindDn without the correct permissions to reset passwords.
