### ISSUE TITLE
Support for Zentyal

### ISSUE THREAD

**Issue by utianayuba** [Zimbra-Community/ADPassword#2]
Hi, Sir.

I try this extension on Zimbra OSE 8.6 and Zentyal 4.2/Samba4 Domain Controller.

This is my configuration

> zimbra@zimbra:~$ zmprov -l gd bogor.ok | grep -i ldap | grep -v GalzimbraAdminConsoleLDAPAuthEnabled: FALSE
> zimbraAuthLdapBindDn: %u@bogor.ok
> zimbraAuthLdapSearchBase: OU=Cimanggu,DC=bogor,DC=ok
> zimbraAuthLdapSearchBindDn: administrator@bogor.ok
> zimbraAuthLdapSearchBindPassword: secret
> zimbraAuthLdapSearchFilter: (samaccountname=%u)
> zimbraAuthLdapURL: ldaps://192.168.100.10:636
> zimbraAutoProvAuthMech: LDAP
> zimbraAutoProvLdapAdminBindDn: administrator@bogor.ok
> zimbraAutoProvLdapAdminBindPassword: secret
> zimbraAutoProvLdapBindDn: administrator@bogor.ok
> zimbraAutoProvLdapSearchBase: ou=Cimanggu,dc=bogor,dc=ok
> zimbraAutoProvLdapSearchFilter: (&(ObjectCategory=person))
> zimbraAutoProvLdapURL: ldap://192.168.100.10:389
> zimbraExternalGroupLdapSearchBase: OU=Cimanggu,DC=bogor,DC=ok
> zimbraExternalGroupLdapSearchFilter: (samaccountname=%u)
> 
> zimbra@zimbra:~$ zmprov -l gd bogor.ok | grep -i zimbraPasswordChangeListener
> zimbraPasswordChangeListener: ADPassword

But password change still denied. The log messages is below

> 2016-05-07 02:06:16,964 WARN  [qtp509886383-643:https://192.168.100.11:8443/h/changepass?skin=harmony] [] webclient - permission denied: javax.naming.NameNotFoundException: [LDAP: error code 32 - 00002030: No such Base DN: cn=mika,OU=Cimanggu,DC=bogor,DC=ok]; remaining name 'cn=mika,OU=Cimanggu,DC=bogor,DC=ok'
> com.zimbra.common.soap.SoapFaultException: permission denied: javax.naming.NameNotFoundException: [LDAP: error code 32 - 00002030: No such Base DN: cn=mika,OU=Cimanggu,DC=bogor,DC=ok]; remaining name 'cn=mika,OU=Cimanggu,DC=bogor,DC=ok'
> ExceptionId:qtp509886383-652:http://127.0.0.1:8080/service/soap/ChangePasswordRequest:1462561576962:f2177f5246f98c0f
> Code:service.PERM_DENIED

Any suggestions on this?

Thank you.

**Comment by ghost** [comment]
Its because _AD_Password changes the password in Windows Active Directory, not on OpenLDAP like systems.

Try this version: 
https://mail.zetalliance.org/owncloud/index.php/s/seJe8NKCAQ7IpiY

  zmprov md domain.ext zimbraPasswordChangeListener OLPassword

In the readme do not follow the AD related steps, so make sure your Zimbra is already doing auth against your LDAP before trying and installing this extension.

@maxxer maybe you can check this openldap version also. Thanks Barry

**Comment by utianayuba** [comment]
Hi, @barrydegraaff and @maxxer

I tried OLPassword extension but fail with log message:

> 2016-05-07 14:13:59,979 WARN  [qtp509886383-117:https://192.168.100.11:8443/h/changepass?skin=harmony] [] webclient - system failure: change password listener OLPassword for account nida@bogor.ok not found
> com.zimbra.common.soap.SoapFaultException: system failure: change password listener OLPassword for account nida@bogor.ok not found
> ExceptionId:qtp509886383-175:http://127.0.0.1:8080/service/soap/ChangePasswordRequest:1462605239976:e95765eb7c8b3720
> Code:service.FAILURE

I did steps:

> utian@zimbra:~$ sudo mkdir -p /opt/zimbra/lib/ext/olpassword/
> utian@zimbra:~$ sudo chmod 775 /opt/zimbra/lib/ext/olpassword/
> utian@zimbra:~$ sudo wget -c http://mail.zetalliance.org/owncloud/index.php/s/seJe8NKCAQ7IpiY/download -O /opt/zimbra/lib/ext/olpassword/OLPassword.jar
> 
> utian@zimbra:~$ sudo su - zimbra
> zimbra@zimbra:~$ zmcontrol restart
> 
> zimbra@zimbra:~$ zmprov -l gd bogor.ok | grep -i ldap | grep -v Gal
> zimbraAdminConsoleLDAPAuthEnabled: FALSE
> zimbraAuthLdapBindDn: %u@bogor.ok
> zimbraAuthLdapSearchBase: CN=Users,DC=bogor,DC=ok
> zimbraAuthLdapSearchBindDn: administrator@bogor.ok
> zimbraAuthLdapSearchBindPassword: secret
> zimbraAuthLdapSearchFilter: (samaccountname=%u)
> zimbraAuthLdapStartTlsEnabled: FALSE
> zimbraAuthLdapURL: ldaps://192.168.100.10:636
> zimbraAuthMech: ldap
> zimbraAuthMechAdmin: ldap
> zimbraExternalGroupLdapSearchBase: CN=Users,DC=bogor,DC=ok
> zimbraExternalGroupLdapSearchFilter: (samaccountname=%u)
> 
> zimbra@zimbra:~$ zmprov -l gd bogor.ok | grep -i zimbraPasswordChangeListener
> zimbraPasswordChangeListener: OLPassword

Did I miss some steps?
Sorry to bother you. Please response this issue only if you have some spare time.
Many thanks.

**Comment by ghost** [comment]
do you use samaccountname?

Anyways, it looks like to debug this I need to install a Zentyal server, and document all the differences, it would take me a day or so.

**Comment by ghost** [comment]
Installed Zentyal

It seems it uses sAMAccountName but puts users in a different DN. 

ldapsearch -LLL -H ldaps:///192.168.100.10:636 -x -b 'CN=Users, DC=BOGOR, DC=OK' -D 'administrator@bogor.ok' -w 'secret'

Google on how to install ldapsearch (on any linux distro)

You need to find out in what what goes behind: -b 'CN=....'

You can also try making a user that has the same value for CN and sAMAccountName, and try to change that password.

Barry

example for my setup:

```
  dn: CN=bar bar,CN=Users,DC=dynamic,DC=ziggo,DC=nl
  cn: bar bar
  sn: bar
  givenName: bar
  instanceType: 4
  whenCreated: 20160507190014.0Z
  displayName: bar bar
  uSNCreated: 5283
  name: bar bar
  objectGUID:: cOvw80BR9E611G854LWDsg==
  badPwdCount: 0
  codePage: 0
  countryCode: 0
  homeDirectory: /home/barry
  badPasswordTime: 0
  lastLogoff: 0
  primaryGroupID: 513
  objectSid:: AQUAAAAAAAUVAAAA0+ftkwyA8LisUZt5UgQAAA==
  accountExpires: 9223372036854775807
  logonCount: 0
  sAMAccountName: barry
  sAMAccountType: 805306368
  userPrincipalName: barry@DYNAMIC.ZIGGO.NL
  objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=dynamic,DC=ziggo,DC=nl
  uidNumber: 2502
  gidNumber: 2513
  quota: 500
  pwdLastSet: 131071212140000000
  userAccountControl: 512
  objectClass: top
  objectClass: fetchmailUser
  objectClass: posixAccount
  objectClass: userZentyalMail
  objectClass: person
  objectClass: systemQuotas
  objectClass: organizationalPerson
  objectClass: user
  mail: barry@dynamic.ziggo.nl
  mailbox: dynamic.ziggo.nl/barry/
  userMaildirSize: 0
  mailquota: 0
  mailHomeDirectory: /var/vmail/
  mailNickname: barry
  homeMDB: CN=Mailbox Store (ZENTYAL),CN=First Storage Group,CN=InformationStore
   ,CN=ZENTYAL,CN=Servers,CN=First Administrative Group,CN=Administrative Groups
   ,CN=First Organization,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=
   dynamic,DC=ziggo,DC=nl
  homeMTA: CN=Mailbox Store (ZENTYAL),CN=First Storage Group,CN=InformationStore
   ,CN=ZENTYAL,CN=Servers,CN=First Administrative Group,CN=Administrative Groups
   ,CN=First Organization,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=
   dynamic,DC=ziggo,DC=nl
  legacyExchangeDN: /o=First Organization/ou=First Administrative Group/cn=Recip
   ients/cn=barry
  proxyAddresses: SMTP:barry@dynamic.ziggo.nl
  proxyAddresses: =EX:/o=First Organization/ou=First Administrative Group/cn=Rec
   ipients/cn=barry
  proxyAddresses: X400:c=US;a= ;p=First Organizati;o=First Administrative Group;
   s=barry
  proxyAddresses: smtp:postmaster@dynamic.ziggo.nl
  msExchUserAccountControl: 0
  msExchRecipientTypeDetails: 6
  msExchRecipientDisplayType: 0
  msExchOmaAdminWirelessEnable: 0
  lastLogon: 131071212441136830
  lastLogonTimestamp: 131071212441136830
  whenChanged: 20160507190044.0Z
  uSNChanged: 5290
  distinguishedName: CN=bar bar,CN=Users,DC=dynamic,DC=ziggo,DC=nl
```

**Comment by ghost** [comment]
so you can use ADPassword, not the patched one, do you have multiple User OU's?

**Comment by utianayuba** [comment]
Hi, @barrydegraaff.

I'm now testing only using single OU and use ADPassword 0.0.2 extension, but still denied like the first time I tried.
I'm using zcs-8.6.0_GA_1153 + zcs-patch-8.6.0_GA_1194 on Ubuntu 14.04.4 LTS.
Looks like the CN on DN contain givenName and SN not only sAMAccountName.

> zimbra@zimbra:~$ ldapsearch -LLL -H ldaps://192.168.100.10:636 -D administrator@bogor.ok -w secret -b CN=Users,DC=bogor,DC=ok
> .....
> dn: CN=jibril jibril,CN=Users,DC=bogor,DC=ok
> objectClass: top
> objectClass: posixAccount
> objectClass: person
> objectClass: systemQuotas
> objectClass: organizationalPerson
> objectClass: user
> cn: jibril jibril
> sn: jibril
> givenName: jibril
> instanceType: 4
> whenCreated: 20160507193450.0Z
> uSNCreated: 3929
> name: jibril jibril
> objectGUID:: 6hcJiKYDWU+P/bVvr8TbTQ==
> badPwdCount: 0
> codePage: 0
> countryCode: 0
> homeDirectory: /home/jibril
> badPasswordTime: 0
> lastLogoff: 0
> primaryGroupID: 513
> objectSid:: AQUAAAAAAAUVAAAAGSb2Dji2hVTz1Z7ZXAQAAA==
> accountExpires: 9223372036854775807
> logonCount: 0
> sAMAccountName: jibril
> sAMAccountType: 805306368
> userPrincipalName: jibril@BOGOR.OK
> objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=bogor,DC=ok
> uidNumber: 2505
> gidNumber: 2513
> quota: 500
> pwdLastSet: 131071232910000000
> userAccountControl: 512
> profilePath: \zentyal.BOGOR.OK\profiles\jibril
> lastLogon: 131071233231466940
> lastLogonTimestamp: 131071233231466940
> whenChanged: 20160508065507.0Z
> uSNChanged: 3951
> distinguishedName: CN=jibril jibril,CN=Users,DC=bogor,DC=ok
> .....
> 
> zimbra@zimbra:~$ zmprov gd bogor.ok | grep -i ldap | grep -v Gal
> zimbraAdminConsoleLDAPAuthEnabled: FALSE
> zimbraAuthLdapBindDn: %u@bogor.ok
> zimbraAuthLdapSearchBase: CN=Users,DC=bogor,DC=ok
> zimbraAuthLdapSearchBindDn: administrator@bogor.ok
> zimbraAuthLdapSearchBindPassword: secret
> zimbraAuthLdapSearchFilter: (samaccountname=%u)
> zimbraAuthLdapURL: ldaps://192.168.100.10:636
> zimbraExternalGroupLdapSearchBase: CN=Users,DC=bogor,DC=ok
> zimbraExternalGroupLdapSearchFilter: (samaccountname=%u)
> 
> zimbra@zimbra:~$ zmprov gd bogor.ok | grep -i zimbraAuthMech
> zimbraAuthMech: ad
> zimbraAuthMechAdmin: ad
> 
> zimbra@zimbra:~$ zmprov gd bogor.ok | grep -i zimbraPasswordChangeListener
> zimbraPasswordChangeListener: ADPassword
> 
> zimbra@zimbra:~$ tailf /opt/zimbra/log/mailbox.log 
> .....
> 2016-05-08 13:51:37,503 WARN  [qtp509886383-121:https://192.168.100.11:8443/h/changepass?skin=harmony] [] webclient - permission denied: javax.naming.NameNotFoundException: [LDAP: error code 32 - 00002030: No such Base DN: cn=jibril,CN=Users,DC=bogor,DC=ok]; remaining name 'cn=jibril,CN=Users,DC=bogor,DC=ok'
> com.zimbra.common.soap.SoapFaultException: permission denied: javax.naming.NameNotFoundException: [LDAP: error code 32 - 00002030: No such Base DN: cn=jibril,CN=Users,DC=bogor,DC=ok]; remaining name 'cn=jibril,CN=Users,DC=bogor,DC=ok'
> ExceptionId:qtp509886383-120:http://127.0.0.1:8080/service/soap/ChangePasswordRequest:1462690297501:a46f4b025555b157
> Code:service.PERM_DENIED
> .....

**Comment by utianayuba** [comment]
I'm using zcs-8.6.0_GA_1153 + zcs-patch-8.6.0_GA_1194 on Ubuntu 14.04.4 LTS

**Comment by ghost** [comment]
Thanks, I am now 100% sure what the problem is, your 
cn:  jibril jibril
This should be: jibril  
It feels like a bug in the ldap schema of Zentyal... again can you make/change the user so that cn = sAMAccountName ?

**Comment by ghost** [comment]
Can you try this version:
https://mail.zetalliance.org/owncloud/index.php/s/qub6V1ld0IJQzxq

**Comment by utianayuba** [comment]
Wow @barrydegraaff,
That one works well (http://mail.zetalliance.org/owncloud/index.php/s/qub6V1ld0IJQzxq/download).

Many thanks.
May God bless you always :)

**Comment by ghost** [comment]
OK if you can consider making a donation, it is MOST appreciated:
PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A

This will allow me to make Zentyal officially supported (and one can set an option in Zimbra LDAP to configure ADPassword for Zentyal)

Thanks!

**Comment by ghost** [comment]
Thanks for your donation, for now I will put the documentation on the wiki:
https://github.com/Zimbra-Community/ADPassword/wiki/Support-for-Zentyal

**Comment by ghost** [comment]
Updated 
https://www.zimbra.org/extend/items/view/active-directory-change-password
https://github.com/Zimbra-Community/ADPassword/blob/master/README.md
