### ISSUE TITLE
Java Runtime version mismatch

### ISSUE THREAD

**Issue by seteq** [Zimbra-Community/ADPassword#21]
Hello,

I'm running Zimbra 8.8.15_GA_3847.FOSS on Centos7 and I get following error in zmmailboxd.out when I follow the installation instructions and restart zimbra. When I try to log on I just get a network error message.

`javax.servlet.UnavailableException: it/iknowconsulting/adpassword/ADPassword has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
`

Thank you

**Comment by ghost** [comment]
After installing Zimbra, make sure to install ALL zimbra patches. This 
extension only works with 8.8.15 patch 5 and above.

To be able to install the patches, remove the adpassword jar first. And 
restart zimbra
