### ISSUE TITLE
com.zimbra.common.service.ServiceException.PERM_DENIED(

### ISSUE THREAD

**Issue by dsacchet** [Zimbra-Community/ADPassword#3]
Hello,

I think I correctly installed and configured ADPassword extension but when I try to change password, I have the following error : 

ExceptionId:qtp509886383-22920:http://127.0.0.1:8080/service/soap/ChangePasswordRequest:1464599365132:e572c8c7531079e2
Code:service.PERM_DENIED
    at com.zimbra.common.service.ServiceException.PERM_DENIED(ServiceException.java:290)
    at it.iknowconsulting.adpassword.ADChangePasswordListener.preModify(ADChangePasswordListener.java:43)
    at com.zimbra.cs.account.ldap.ChangePasswordListener.invokePreModify(ChangePasswordListener.java:128)
    at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:5707)
    at com.zimbra.cs.account.ldap.LdapProvisioning.changePassword(LdapProvisioning.java:5375)
    at com.zimbra.cs.service.account.ChangePassword.handle(ChangePassword.java:95)
    at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:564)

After two days of google search, I don't find solution for my issue :(

Do you have an idea ?

Thanks in advance

Best regards

Denis Sacchet

**Comment by dsacchet** [comment]
Re,

finally I found additional informations in log :

com.zimbra.common.service.ServiceException: permission denied: javax.naming.InvalidNameException: cn=intervenant,**null**: [LDAP: error code 34 - 0000208F: NameErr: DSID-031001F7, problem 2006 (BAD_NAME), data 8350, best match of:
    'cn=intervenant,**null**'

It seems the line 47 from ADConnection.java doesn't work for me :

authLdapSearchBase = domain.getAuthLdapSearchBase();

But the configuration is "correct" (i replace my domain by domain.com) :

imbra@zimbra:~$ zmprov gd domain.com | grep -i ldap | grep -v Gal
zimbraAdminConsoleLDAPAuthEnabled: FALSE
zimbraAuthLdapBindDn: %u@domain.com
zimbraAuthLdapSearchBindDn: zimbraadm@domain.com
zimbraAuthLdapSearchBindPassword: zimbraadm
zimbraAuthLdapSearchFilter: (samaccountname=%u)
zimbraAuthLdapURL: ldaps://ad.domain.com:636
zimbraExternalGroupLdapSearchBase: OU=Utilisateurs Jury,DC=domain,DC=com
zimbraExternalGroupLdapSearchFilter: (samaccountname=%u)
[ZIMBRA 8.5] zimbra@zimbra:~$ 

Thanks for your help

Denis Sacchet

**Comment by ghost** [comment]
Yep, it seems like your configuration is ALL wrong, OR you try to do something that is not tested, can you follow the instructions here:
https://github.com/Zimbra-Community/ADPassword#installation-via-the-cli

The error you get is for incorrect zimbraAuthLdapSearchBindDn

**Comment by dsacchet** [comment]
Hello,

I'm sorry, but I think the problem is in the construction of the username, the test I made is with the user "intervenant" and I have the following error in the log :

2016-05-31 22:43:07,574 INFO  [qtp509886383-166:http://127.0.0.1:8080/service/soap/ChangePasswordRequest] [ip=127.0.0.1;ua=zclient/8.5.1_GA_3056;] SoapEngine - handler exception
com.zimbra.common.service.ServiceException: permission denied: javax.naming.InvalidNameException: cn=**intervenant**,null: [LDAP: error code 34 - 0000208F: NameErr: DSID-031001F7, problem 2006 (BAD_NAME), data 8350, best match of:
    'cn=**intervenant**,null'

It is like if it doesn't take the zimbraExternalGroupLdapSearchBase parameter. I tried to change because of the space present in the string, but even without space, it still doesn't work.

**Comment by ghost** [comment]
I think setting zimbraExternalGroupLdapSearchBase, does nothing, it is something I left in the documentation from the original version.

Are you using multiple OU's? In that case try:
https://github.com/ronaldomaya/ADPassword

In any other case, forget about zimbraExternalGroupLdapSearchBase and set zimbraAuthLdapSearchBase
