### ISSUE TITLE
How to change a expired password?

### ISSUE THREAD

**Issue by elieser-topassi** [Zimbra-Community/ADPassword#7]
Hi,
It's possible change a expired password?
I've tried it, and the login on zimbra fails...

**Comment by ghost** [comment]
Nope, that does not work as Zimbra authenticates against your AD and that says NO the account is expired.

If the user had a different way of logging into zimbra, then it could use the zimbraAuthLdapSearchBindDn credentials to reset the password.

But the code was not intended for this purpose.

Sorry
