### ISSUE TITLE
Hi, trying for 8.8.6 FOSS

### ISSUE THREAD

**Issue by lethanhf** [Zimbra-Community/ADPassword#8]
Permission Denied
com.zimbra.common.soap.SoapFaultException: permission denied: javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT),
...
Code:service.PERM_DENIED

**Comment by ghost** [comment]
Hello, 

This means that the ad-password extension tries to find an object in your ldap, but it cannot find it or does not have permission to it. Usually it means you made an error configuring it OR your ldap structure is not understood.

If you want, I can debug it later, contact me at info@barrydegraaff.tk to discuss options.

Barry

**Comment by lethanhf** [comment]
thanks barrydegraaff, after make correct ldap strings it is wroking

**Comment by llanlago** [comment]
> thanks barrydegraaff, after make correct ldap strings it is wroking

Hello @lethanhf! 

I'm having the same problem, could you share you configuration please?

Thank You!
